[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/headzoo/surf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/txgruppi/werr"

[[constraint]]
  name = "gopkg.in/headzoo/surf.v1"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
